name: Quibble

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  quibble:
    env:
      MEDIAWIKI_VERSION: master
      DOCKER_REGISTRY: docker-registry.wikimedia.org
      DOCKER_ORG: releng
      DOCKER_IMAGE: quibble-stretch-php73

      # includes deps of deps
      # @todo auto generate below by inspecting https://raw.githubusercontent.com/wikimedia/integration-config/master/zuul/parameter_functions.py
      DEPENDENCIES: >-
        mediawiki/extensions/BetaFeatures
        mediawiki/extensions/Echo
        mediawiki/extensions/CentralAuth
        mediawiki/extensions/EventLogging
        mediawiki/extensions/EventStreamConfig

    strategy:
      matrix:
        stage:
          - phpunit-unit
          - phpunit
          - phpunit-standalone
          - npm-test
          - composer-test
          # - qunit
          # - selenium
          # - api-testing

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # /home/runner/cache/                           Cache
      # /home/runner/src/                             Mediawiki installation
      # /home/runner/src/extensions/EXTENSION_NAME/   Clone of this repository
      # /home/runner/docker-images/                   Docker images which exported with docker-save command
      # $GITHUB_WORKSPACE/.dependencies               Used by actions/cache
      - name: Set up
        run: |
          # Get the latest docker tag (Ref: https://github.com/thcipriani/dockerregistry)
          echo "DOCKER_LATEST_TAG=$(curl -sL "https://${DOCKER_REGISTRY}/v2/${DOCKER_ORG}/${DOCKER_IMAGE}/tags/list" |
            python3 -c 'import json;print("\n".join(json.loads(input())["tags"]))' |
            grep -v latest | sort -Vr | head -1)" >> $GITHUB_ENV

          # Used by actions/cache
          echo $DEPENDENCIES > .dependencies

          # Make directories
          cd /home/runner
          mkdir -p cache
          chmod 777 cache

      - name: Cache docker image
        uses: actions/cache@v2
        with:
          path: /home/runner/docker-images/${{ env.DOCKER_IMAGE }}
          key: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_LATEST_TAG }}
      - name: Load or pull docker image
        run: |
          docker load -i /home/runner/docker-image/"${DOCKER_ORG}/${DOCKER_IMAGE}" || \
            docker pull "${DOCKER_REGISTRY}/${DOCKER_ORG}/${DOCKER_IMAGE}:${DOCKER_LATEST_TAG}"

      - name: Cache MediaWiki installation
        uses: actions/cache@v2
        with:
          path: /home/runner/src
          key: ${{ env.MEDIAWIKI_VERSION }}-${{ hashFiles('.dependencies') }}
      - name: Download MediaWiki and extensions
        run: |
          cd /home/runner
          if [ ! -d src ]; then
            git clone -b "${MEDIAWIKI_VERSION}" --depth 1 https://gerrit.wikimedia.org/r/mediawiki/core src
            git clone --recurse-submodules -b "${MEDIAWIKI_VERSION}" --depth 1 https://gerrit.wikimedia.org/r/mediawiki/skins/Vector src/skins/Vector
            for dep in $DEPENDENCIES; do
              git clone --recurse-submodules -b "${MEDIAWIKI_VERSION}" --depth 1 "https://gerrit.wikimedia.org/r/${dep}" src/"$(echo $dep | cut -d'/' -f2,3)"
            done
          fi

      - name: Cache dependencies (composer and npm)
        uses: actions/cache@v2
        with:
          path: /home/runner/cache
          key: "${{ runner.os }}-${{ env.MEDIAWIKI_VERSION }}-${{ hashFiles('**/*.lock') }}"
      - name: Run Quibble
        run: |
          cd /home/runner
          # Move our extension
          sudo cp -r "${GITHUB_WORKSPACE}" src/extensions/
          chmod 777 src
          sudo chown -R nobody:nogroup src cache
          sudo chown $(id -u):$(id -g) src cache
          docker run \
            -e ZUUL_PROJECT=mediawiki/extensions/"${{ github.event.repository.name }}" \
            -v "$(pwd)"/cache:/cache \
            -v "$(pwd)"/src:/workspace/src \
            "${DOCKER_REGISTRY}/${DOCKER_ORG}/${DOCKER_IMAGE}:${DOCKER_LATEST_TAG}" \
            --skip-zuul \
            --packages-source composer \
            --run "${{ matrix.stage }}" \
            $DEPENDENCIES

      - name: Tear down
        run: |
          cd /home/runner
          # See https://doc.wikimedia.org/quibble/index.html#remove-localsettings-php-between-runs
          rm "$(pwd)"/src/LocalSettings.php
          mkdir -p docker-images
          docker save -o "$(pwd)/docker-images/${DOCKER_IMAGE}" "${DOCKER_REGISTRY}/${DOCKER_ORG}/${DOCKER_IMAGE}:${DOCKER_LATEST_TAG}"
